name: CoordLeak
version: 'v0.1-beta3'
main: com.qhuy.coordLeak.CoordLeak
api-version: '1.21'
load: POSTWORLD
authors: [ qhuy ]
description: Allows players to buy usages to leak the coordinates of random online players.
depend: [Vault]
softdepend: [Essentials, PlaceholderAPI]
libraries:
  - net.dv8tion:JDA:6.1.1
permissions:
  coordleak.admin:
    default: op
  coordleak.use:
    default: true
commands:
  coord:
    usage: /coord
    description: Leak the coordinates of a random online player.
    permission: coordleak.use
