name: CoordLeak
version: 'v1.0.0'
main: com.qhuy.coordLeak.CoordLeak
api-version: '1.21'
load: POSTWORLD
authors: [ qhuy ]
description: Production-grade plugin for coordinate leaking and sharing with economy integration
depend: [Vault]
softdepend: [Essentials, PlaceholderAPI]
libraries:
  - net.kyori:adventure-platform-bukkit:4.4.1
  - net.kyori:adventure-api:4.24.0
  - net.kyori:adventure-text-minimessage:4.24.0
permissions:
  coordleak.*:
    description: Grants all CoordLeak permissions
    default: op
    children:
      coordleak.admin: true
      coordleak.leak: true
      coordleak.share: true
      coordleak.setprice: true
      coordleak.bypass.*: true
  coordleak.admin:
    description: Admin permission for reload and management
    default: op
  coordleak.leak:
    description: Allows leaking random player coordinates
    default: true
  coordleak.share:
    description: Allows sharing your coordinates
    default: true
  coordleak.setprice:
    description: Allows setting the leak price
    default: op
  coordleak.bypass.*:
    description: Grants all bypass permissions
    default: op
    children:
      coordleak.bypass.cooldown: true
      coordleak.bypass.ratelimit: true
      coordleak.bypass.dailylimit: true
  coordleak.bypass.cooldown:
    description: Bypass cooldown restrictions
    default: op
  coordleak.bypass.ratelimit:
    description: Bypass rate limit restrictions
    default: op
  coordleak.bypass.dailylimit:
    description: Bypass daily limit restrictions
    default: op
commands:
  coord:
    usage: /coord [leak|share|reload|setprice|info]
    description: Main command for CoordLeak plugin. Use /coord setprice <amount> to set the price.
    permission: coordleak.leak
