name: CoordLeak
version: 'v0.1-beta3'
main: com.qhuy.coordLeak.CoordLeak
api-version: '1.21'
load: POSTWORLD
authors: [ qhuy ]
description: Allows players to buy usages to leak the coordinates of random online players.
depend: [Vault]
softdepend: [Essentials, PlaceholderAPI]
libraries:
  - net.kyori:adventure-platform-bukkit:4.4.1
  - net.kyori:adventure-api:4.24.0
  - net.kyori:adventure-text-minimessage:4.24.0
permissions:
  coordleak.admin:
    default: op
  coordleak.leak:
    default: true
  coordleak.share:
    default: true
  coordleak.setprice:
    default: op
commands:
  coord:
    usage: /coord
    description: Main command for CoordLeak plugin.
    permission: coordleak.leak
  setprice:
    usage: /setprice <amount>
    description: Set the price for leaking coordinates.
    permission: coordleak.setprice
